2022-04-27 10:28:57,549 INFO  ==============================================================
2022-04-27 10:28:57,550 INFO  Id:    custom_init_system
2022-04-27 10:28:57,551 INFO  Dir:   misc_features/
2022-04-27 10:28:57,552 INFO  Title: Custom init system test
2022-04-27 10:28:57,553 INFO  ==============================================================
2022-04-27 10:28:58,123 INFO  Executed sudo<copy_system_config>, exit status 0
2022-04-27 10:28:58,739 INFO  Executed sudo<copy_dummy_init>, exit status 0
2022-04-27 10:28:59,305 WARN  Executed sudo<tedge_connect>, exit status 1
2022-04-27 10:28:59,310 INFO  Contents of tedge_connect.err: 
2022-04-27 10:28:59,311 INFO    Error: failed to connect Cumulocity cloud.
2022-04-27 10:28:59,312 INFO    Caused by:
2022-04-27 10:28:59,313 INFO        A value for `c8y.url` is missing.
2022-04-27 10:28:59,313 INFO            A value can be set with `tedge config set c8y.url <value>`
2022-04-27 10:28:59,314 INFO    -----
2022-04-27 10:28:59,315 INFO  
2022-04-27 10:28:59,337 WARN  sudo<tedge_connect> returned non-zero exit code 1 ... blocked [run.py:53]
2022-04-27 10:28:59,339 WARN  Aborted test due to BLOCKED outcome
2022-04-27 10:28:59,343 INFO  
2022-04-27 10:28:59,344 INFO  cleanup:
2022-04-27 10:28:59,856 INFO  Executed sudo<remove_system_config>, exit status 0
2022-04-27 10:29:00,368 INFO  Executed sudo<remove_dummy_init>, exit status 0
2022-04-27 10:29:00,372 INFO  
2022-04-27 10:29:00,373 INFO  Test duration: 2.83 secs
2022-04-27 10:29:00,374 INFO  Test final outcome:  BLOCKED
2022-04-27 10:29:00,375 INFO  Test outcome reason: sudo<tedge_connect> returned non-zero exit code 1
2022-04-27 10:29:00,376 INFO  
