2022-04-27 10:28:21,305 INFO  ==============================================================
2022-04-27 10:28:21,306 INFO  Id:    c8y_jwt_token_retrieval
2022-04-27 10:28:21,310 INFO  Dir:   cloud_c8y/
2022-04-27 10:28:21,311 INFO  Title: Validate the Cumulocity JWT Token Retrieval feature
2022-04-27 10:28:21,312 INFO  ==============================================================
2022-04-27 10:28:22,191 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-04-27 10:28:22,804 WARN  Executed sudo<tedge_connect_c8y>, exit status 1
2022-04-27 10:28:22,812 INFO  Contents of tedge_connect_c8y.err: 
2022-04-27 10:28:22,814 INFO    Error: failed to connect Cumulocity cloud.
2022-04-27 10:28:22,814 INFO    Caused by:
2022-04-27 10:28:22,815 INFO        A value for `c8y.url` is missing.
2022-04-27 10:28:22,816 INFO            A value can be set with `tedge config set c8y.url <value>`
2022-04-27 10:28:22,816 INFO    -----
2022-04-27 10:28:22,817 INFO  
2022-04-27 10:28:22,989 WARN  sudo<tedge_connect_c8y> returned non-zero exit code 1 ... blocked [environment_tedge.py:58,run.py:31]
2022-04-27 10:28:22,990 WARN  Aborted test due to BLOCKED outcome
2022-04-27 10:28:22,996 INFO  
2022-04-27 10:28:22,997 INFO  cleanup:
2022-04-27 10:28:23,609 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-04-27 10:28:23,614 INFO  
2022-04-27 10:28:23,614 INFO  Test duration: 2.31 secs
2022-04-27 10:28:23,616 INFO  Test final outcome:  BLOCKED
2022-04-27 10:28:23,616 INFO  Test outcome reason: sudo<tedge_connect_c8y> returned non-zero exit code 1
2022-04-27 10:28:23,617 INFO  
