<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="SoftwareManagement.Plugin.apama_plugin_install" skipped="0" tests="1" time="7.51" timestamp="2022-04-27T09:16:20">
	<testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install">
		<failure message="BLOCKED: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+1 other failures)" type="BLOCKED"/>
		<system-out>09:16:12 INFO  ==============================================================
09:16:12 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_install
09:16:12 INFO  Dir:   plugin_apama/
09:16:12 INFO  Title: Validate apama plugin install
09:16:12 INFO  ==============================================================
09:16:12 INFO  Assertion that path exists=False for &quot;/etc/tedge/apama/project&quot; ... passed
09:16:17 INFO  Executed sudo&lt;plugin_install&gt;, exit status 0
09:16:17 INFO  Executed sudo&lt;apama_correlator_wait&gt;, exit status 0
09:16:18 INFO  Executed sudo&lt;plugin_list_after_install&gt;, exit status 0
09:16:18 INFO  Assertion that path exists=True for &quot;/etc/tedge/apama/project&quot; ... passed
09:16:19 INFO  Executed sudo&lt;apama_list_monitors&gt;, exit status 0
09:16:19 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/apama_plugin_install/Output/linux/apama_list_monitors.out ... passed
09:16:19 INFO  Grep on file plugin_list_after_install.out ... passed
09:16:19 INFO  Grep on file plugin_list_after_install.out ... passed
09:16:19 INFO  
09:16:19 INFO  cleanup:
09:16:19 INFO  Removing apama project
09:16:19 WARN  Executed sudo&lt;remove_apama_project&gt;, exit status 1
09:16:19 INFO  Contents of remove_apama_project.err: 
  rm: cannot remove '/etc/tedge/apama/project/logs': Directory not empty
  -----

09:16:20 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py&quot;, line 1305, in cleanup
    fn()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py&quot;, line 144, in cleanup_project
    self.remove_project()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py&quot;, line 95, in remove_project
    stdouterr=&quot;remove_apama_project&quot;,
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py&quot;, line 482, in startProcess
    abortOnError=abortOnError)
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py&quot;, line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py&quot;, line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1
09:16:20 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (AbortExecution) ... blocked 
09:16:20 INFO  
09:16:20 INFO  Test duration: 7.51 secs
09:16:20 INFO  Test final outcome:  BLOCKED
09:16:20 INFO  Test outcome reason: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (+1 other failures)
09:16:20 INFO  
</system-out>
	</testcase>
</testsuite>
